Cho thực thi và in giá trị của các tham số này để kiểm tra.
42. Cho biết có bao nhiêu trận đấu hòa nhau ở vòng 3 năm 2009.
43. Viết store procedure tương ứng với các câu ở phần View. Sau đó cho thực hiện để kiểm
tra kết quả.
44. Viết các thủ tục để nhập số liệu cho CSDL trên (các số liệu được thêm vào thông qua
tham số thủ tục).
45. Nhập vào mã cầu thủ (@MaCT), cho biết thông tin các trận đấu (MaTD, TenTD,
NgayTD) mà cầu thủ này đã tham gia.
46. Nhập vào mã trận đấu (@MaCT), cho biết danh sách cầu thủ ghi bàn trong trận đấu này.
47. Cho biết có tất cả bao nhiêu trận đấu hòa nhau.